import { Sql } from 'postgres';

export type Session = {
  id: number;
  token: string;
  userId: number;
};

export async function up(sql: Sql) {
  await sql`
  CREATE TABLE sessions (
    id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    token varchar(150) NOT NULL UNIQUE,
    --  will be generated automatically
    --  DEFAULT value will be generated by postgres, if u dont pass it
    --  NOW() means evrytime u create a new record, timestamp is going to be the moment of the creation
    --  INTERVAL OF 24 HOURS means sessions will have 24 hours of validity after the creation
    expiry_timestamp timestamp NOT NULL DEFAULT NOW() + INTERVAL '24 hours',
    --  ON DELETE CASCADE means once the user(id) referenced is deleted, it will also be deleted
    user_id integer REFERENCES users (id) ON DELETE CASCADE
  ) `;
}

export async function down(sql: Sql) {
  await sql`
  DROP TABLE sessions
  `;
}
